---
apiVersion: v1
kind: Service
metadata:
  name: app-conversao-temperatura
  namespace: app-conversao-temperatura
spec:
  selector:
    app: app-conversao-temperatura
  ports:
  - port: 8080  
    targetPort: 8080

